(load "~/.emacs.d/theme.el")
(load "~/.emacs.d/user.el")
(load "~/.emacs.d/preferences.el")
(load "~/.emacs.d/os.el")

(load "~/.emacs.d/company.el")
(load "~/.emacs.d/dap.el")
(load "~/.emacs.d/docker.el")
(load "~/.emacs.d/flycheck.el")
(load "~/.emacs.d/helm.el")
(load "~/.emacs.d/lsp.el")
(load "~/.emacs.d/dumb-jump.el")
(load "~/.emacs.d/magit.el")
(load "~/.emacs.d/projectile.el")

(load "~/.emacs.d/elixir.el")
(load "~/.emacs.d/rust.el")
